// <auto-generated />
namespace Saleular.DAL.SaleularMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class migration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration2));
        
        string IMigrationMetadata.Id
        {
            get { return "201403080327485_migration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
