// <auto-generated />
namespace Saleular.DAL.SaleularMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddEnhancements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEnhancements));
        
        string IMigrationMetadata.Id
        {
            get { return "201503100217078_AddEnhancements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
