namespace Saleular.Migrations
{
    using Saleular.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Saleular.DAL.SaleularContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(Saleular.DAL.SaleularContext context)
        {
            //  This method will be called after migrating to the latest version.

            var phones = new List<Phone>
            {
                // iPhone 5S 64 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity = "64 GB", 
                            Condition = "Flawless", 
                            Price = 455.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 430.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },         
     
                // iPhone 5S 32 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 420.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 395.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 
        
                // iPhone 5S 16 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 390.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 365.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 64 GB Other
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 430.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 405.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 32 GB Other
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 400.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 375.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 16 GB Other
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 370.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 345.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 64 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 455.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 430.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 32 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 420.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 395.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 16 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 390.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 365.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 64 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 450.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 425.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 32 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 420.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 395.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 16 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 390.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 365.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 64 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 430.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 405.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 32 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 400.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 375.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 16 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 370.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 345.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 64 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 450.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 425.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" }, 

                // iPhone 5S 32 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 420.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 395.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

                // iPhone 5S 16 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 390.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 365.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

               new Phone { Type = "iPhone",   
                            Model = "5S", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone5S" },

                // iPhone 5C 32 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 335.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 320.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 16 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 335.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 320.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 32 GB Other
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 335.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 320.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 16 GB Other
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 308.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 290.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 32 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 335.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 340.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 16 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 325.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 310.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 32 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 355.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 340.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 16 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 325.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 310.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 32 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 335.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 320.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 16 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 305.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 290.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 32 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 355.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 340.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5C 32 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 325.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 310.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

               new Phone { Type = "iPhone",   
                            Model = "5C", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone5C" },

                // iPhone 5 64 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 300.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 290.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 32 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 295.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 285.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 16 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 290.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 280.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 64 GB Other
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 230.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 220.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 32 GB Other
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 225.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 215.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 16 GB Other
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 220.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 210.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 64 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 310.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 300.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 32 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 305.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 295.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 16 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 300.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 290.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 64 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 280.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 270.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 32 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 270.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 260.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 16 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 260.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 250.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 64 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 230.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 220.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 16 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 225.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 215.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 16 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 220.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 210.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 64 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 300.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 290.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 32 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 295.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 285.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 5 16 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 290.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 280.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

               new Phone { Type = "iPhone",   
                            Model = "5", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 120.00M,
                            ImageUrl="/Images/iPhones/iPhone5" },

                // iPhone 4S 16 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 195.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 185.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "TMobile", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 8 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "TMobile", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 195.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "TMobile", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 185.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "TMobile", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 64 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 195.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 185.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 32 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 190.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 180.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 16 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 185.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 175.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 64 GB Other
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 145.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 65.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 32 GB Other
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 145.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 65.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 16 GB Other
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 145.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 135.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Other", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 65.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 64 GB Version
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 175.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 155.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 70.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 32 GB Version
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 170.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 160.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 70.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 16 GB Version
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 155.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Version", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 70.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 64 GB Version
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 175.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 70.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 32 GB Version
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 170.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 160.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 70.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 16 GB Version
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 165.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 155.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "Sprint", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 75.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 64 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Flawless", 
                            Price = 195.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Good",
                            Price = 185.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="64 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 32 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 190.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 180.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 16 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 185.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 175.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4S 8 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 180.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 170.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

               new Phone { Type = "iPhone",   
                            Model = "4S", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 80.00M,
                            ImageUrl="/Images/iPhones/iPhone4S" },

                // iPhone 4 8 GB TMobile
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "TMobile", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 115.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "TMobile", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 110.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "TMobile", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 55.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 32 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 115.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 110.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 55.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 16 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 115.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 110.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 55.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 8 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 105.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 100.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 55.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 8 GB Sprint
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Sprint", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 70.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Sprint", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 65.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Sprint", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 25.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 32 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 87.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 82.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 35.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 16 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 90.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 85.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 40.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 8 GB Verizon
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 70.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 65.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Verizon", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 25.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 8 GB Other
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Other", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 60.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Other", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 55.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Other", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 25.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 32 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 105.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 100.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 55.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 16 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 105.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 100.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 55.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 4 8 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 105.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 100.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

               new Phone { Type = "iPhone",   
                            Model = "4", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 55.00M,
                            ImageUrl="/Images/iPhones/iPhone4" },

                // iPhone 3GS 32 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 12.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 8.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

                // iPhone 3GS 16 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 12.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 8.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" }, 
              
                // iPhone 3GS 8 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 12.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 8.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" }, 

                // iPhone 3GS 32 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Good",
                            Price = 12.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="32 GB", 
                            Condition="Bad", 
                            Price = 8.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" }, 

                // iPhone 3GS 16 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 12.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 8.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" }, 

                // iPhone 3GS 8 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 12.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" },

               new Phone { Type = "iPhone",   
                            Model = "3GS", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 8.00M,
                            ImageUrl="/Images/iPhones/iPhone3GS" }, 

                // iPhone 3G 16 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" },

               new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 10.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" },

               new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "ATT", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 1.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" }, 

                // iPhone 3G 8 GB ATT
                new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" },

               new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 10.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" },

               new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "ATT", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 1.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" }, 

                // iPhone 3G 16 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" },

               new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Good",
                            Price = 10.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" },

               new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "Factory", 
                            Capacity="16 GB", 
                            Condition="Bad", 
                            Price = 1.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" }, 

                // iPhone 3G 8 GB Factory
                new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Flawless", 
                            Price = 15.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" },

               new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Good",
                            Price = 10.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" },

               new Phone { Type = "iPhone",   
                            Model = "3G", 
                            Carrier = "Factory", 
                            Capacity="8 GB", 
                            Condition="Bad", 
                            Price = 1.00M,
                            ImageUrl="/Images/iPhones/iPhone3G" }
              
            };
            phones.ForEach(s => context.Phones.AddOrUpdate(p => p.PhoneID, s));
            context.SaveChanges();
        }
    }
}
